export * from './ping.js';
export * from './language.js';
export * from './register.js';
export * from './legal.js';
export * from './about.js';
export * from './rank.js';
export * from './set-rank.js';
export * from './data.js';
export * from './maintenance.js';
